#!/bin/bash
# deploy.sh — initial Hostinger VPS setup for BC Local Government Council Tracker
# Run once as root on a fresh Ubuntu 22.04 VPS:
#   bash deploy/deploy.sh
#
# Prerequisites:
#   - Ubuntu 22.04 VPS with SSH access
#   - A domain pointed at the server's IP (for SSL)
#   - Your GitHub repo accessible (public or SSH key configured)

set -euo pipefail

REPO_URL="https://github.com/toogoodforaname11/lg-tracking.git"
APP_DIR="/var/www/lg-tracking"
PYTHON="python3.11"
DOMAIN="lg-tracker.ca"   # Your domain — change if needed

# --- PostgreSQL credentials (used to create the local database) ---
DB_NAME="lg_tracking"
DB_USER="lg_user"
DB_PASS="$(openssl rand -base64 24)"  # auto-generated; printed at the end

echo "=== BC Local Government Council Tracker — Hostinger VPS Deploy ==="

# --- System packages ---
apt-get update -q
apt-get install -y python3.11 python3.11-venv python3.11-dev \
    nginx certbot python3-certbot-nginx \
    git curl build-essential libpq-dev \
    postgresql postgresql-contrib

# --- Node.js 20.x (for frontend build) ---
if ! command -v node &> /dev/null; then
    echo "Installing Node.js 20.x..."
    curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
    apt-get install -y nodejs
fi
echo "Node.js version: $(node --version)"
echo "npm version: $(npm --version)"

# --- PostgreSQL setup ---
echo "Setting up PostgreSQL..."
systemctl enable postgresql
systemctl start postgresql

# Create database and user (idempotent — skips if they already exist)
sudo -u postgres psql -tc "SELECT 1 FROM pg_roles WHERE rolname='$DB_USER'" \
    | grep -q 1 || sudo -u postgres psql -c "CREATE USER $DB_USER WITH PASSWORD '$DB_PASS';"
sudo -u postgres psql -tc "SELECT 1 FROM pg_database WHERE datname='$DB_NAME'" \
    | grep -q 1 || sudo -u postgres psql -c "CREATE DATABASE $DB_NAME OWNER $DB_USER;"
sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE $DB_NAME TO $DB_USER;"

echo "PostgreSQL ready: database=$DB_NAME user=$DB_USER"

# --- App directory ---
mkdir -p "$APP_DIR"
chown www-data:www-data "$APP_DIR"

# --- Clone / pull repo ---
if [ -d "$APP_DIR/.git" ]; then
    echo "Repo exists — pulling latest..."
    sudo -u www-data git -C "$APP_DIR" pull
else
    echo "Cloning repo..."
    sudo -u www-data git clone "$REPO_URL" "$APP_DIR"
fi

# --- Python virtual environment ---
if [ ! -d "$APP_DIR/venv" ]; then
    echo "Creating virtual environment..."
    sudo -u www-data $PYTHON -m venv "$APP_DIR/venv"
fi

echo "Installing Python dependencies..."
sudo -u www-data "$APP_DIR/venv/bin/pip" install --upgrade pip
sudo -u www-data "$APP_DIR/venv/bin/pip" install -r "$APP_DIR/backend/requirements.txt"

# --- Frontend build (static export) ---
echo "Building frontend..."
cd "$APP_DIR/frontend"
sudo -u www-data npm install
sudo -u www-data STATIC_EXPORT=true npm run build
cd -
echo "Frontend built → $APP_DIR/frontend/out/"

# --- Generate .env with local Postgres pre-configured ---
if [ ! -f "$APP_DIR/backend/.env" ]; then
    CRON_SECRET="$(openssl rand -base64 32)"
    APP_BASE_URL=""
    if [ -n "$DOMAIN" ]; then
        APP_BASE_URL="https://$DOMAIN"
    fi

    cat > "$APP_DIR/backend/.env" <<ENVEOF
# Auto-generated by deploy.sh — edit to add your API keys and email credentials

# PostgreSQL (local — auto-configured)
DATABASE_URL=postgresql+asyncpg://${DB_USER}:${DB_PASS}@localhost:5432/${DB_NAME}
DATABASE_URL_SYNC=postgresql://${DB_USER}:${DB_PASS}@localhost:5432/${DB_NAME}

# Gemini (add your API key to enable AI matching and summarization)
GEMINI_API_KEY=
GEMINI_MODEL=gemini-2.5-flash

# Perplexity (add your API key to enable claim verification)
PERPLEXITY_API_KEY=

# SMTP — Hostinger email (add your email credentials)
SMTP_HOST=smtp.hostinger.com
SMTP_PORT=465
SMTP_USERNAME=
SMTP_PASSWORD=
SMTP_FROM_EMAIL=BC Local Government Council Tracker <noreply@lg-tracker.ca>

# App base URL (auto-set from DOMAIN)
APP_BASE_URL=${APP_BASE_URL}

# CORS
ALLOWED_ORIGINS=http://localhost:3000${APP_BASE_URL:+,$APP_BASE_URL}

# Cron secret (auto-generated)
CRON_SECRET=${CRON_SECRET}

# Debug
DEBUG=false
ENVEOF

    chown www-data:www-data "$APP_DIR/backend/.env"
    chmod 600 "$APP_DIR/backend/.env"
    echo ".env created with local Postgres credentials."
else
    echo ".env already exists — skipping (not overwritten)."
fi

# --- systemd service ---
cp "$APP_DIR/deploy/bc-hearing-watch.service" /etc/systemd/system/
systemctl daemon-reload
systemctl enable bc-hearing-watch

# --- nginx ---
if [ -n "$DOMAIN" ]; then
    sed "s/yourdomain.com/$DOMAIN/g" "$APP_DIR/deploy/nginx.conf" \
        > /etc/nginx/sites-available/lg-tracking
    ln -sf /etc/nginx/sites-available/lg-tracking /etc/nginx/sites-enabled/lg-tracking
    rm -f /etc/nginx/sites-enabled/default
    nginx -t && systemctl reload nginx

    echo "Setting up SSL with Certbot for $DOMAIN..."
    certbot --nginx -d "$DOMAIN" --non-interactive --agree-tos -m "admin@$DOMAIN"
else
    echo "DOMAIN not set — skipping nginx and SSL config."
    echo "Edit DOMAIN= at the top of this script and re-run, or configure nginx manually."
fi

# --- Cron jobs (auto-install with generated secret) ---
if [ -f "$APP_DIR/backend/.env" ]; then
    CRON_SECRET_VAL=$(grep '^CRON_SECRET=' "$APP_DIR/backend/.env" | cut -d= -f2-)
    if [ -n "$CRON_SECRET_VAL" ]; then
        sed "s|<YOUR_CRON_SECRET>|$CRON_SECRET_VAL|g" "$APP_DIR/deploy/crontab" \
            | crontab -u www-data -
        echo "Cron jobs installed for www-data."
    fi
fi

# --- Log files ---
touch /var/log/lg-tracking-poll.log /var/log/lg-tracking-digest.log
chown www-data:www-data /var/log/lg-tracking-poll.log /var/log/lg-tracking-digest.log

# --- Start the service ---
systemctl start bc-hearing-watch
sleep 2

echo ""
echo "=== Deploy complete ==="
echo ""
echo "PostgreSQL credentials (save these):"
echo "  Database: $DB_NAME"
echo "  User:     $DB_USER"
echo "  Password: $DB_PASS"
echo ""
echo "What's already done:"
echo "  - PostgreSQL installed and running with local database"
echo "  - .env created with database credentials and cron secret"
echo "  - Frontend built and served by Nginx"
echo "  - Backend running via systemd"
echo "  - Cron jobs installed (poll every 30 min, weekly digest)"
if [ -n "$DOMAIN" ]; then
echo "  - SSL configured for $DOMAIN"
fi
echo ""
echo "To finish setup, add your credentials to .env:"
echo "  nano $APP_DIR/backend/.env"
echo ""
echo "  You need to add:"
echo "    SMTP_USERNAME=your-hostinger-email@yourdomain.com"
echo "    SMTP_PASSWORD=your-email-password"
echo "    GEMINI_API_KEY=your-gemini-api-key        (optional)"
echo "    PERPLEXITY_API_KEY=your-perplexity-key    (optional)"
echo ""
echo "Then restart and seed:"
echo "  systemctl restart bc-hearing-watch"
echo "  curl -X POST http://127.0.0.1:8000/api/v1/seed"
echo "  curl http://127.0.0.1:8000/health"
